### ISSUE TITLE
Visual issues with skinsdb

### ISSUE THREAD

**Issue by appgurueu** [appgurueu/character_anim#2]
https://forum.minetest.net/viewtopic.php?p=395387#p395387

**Comment by appgurueu** [comment]
See also https://github.com/sfence/clothing/issues/3. Perhaps fixed by the switch to B3D.

**Comment by sfence** [comment]
Tested with the result:

https://user-images.githubusercontent.com/17455197/167987525-52224b55-f215-46a9-a8fb-f8131d643e07.mp4

So, looks fine for the static player, but something happens when the player starts to move.

**Comment by appgurueu** [comment]
Have you upgraded both character_anim and **modlib**?

**Comment by appgurueu** [comment]
![Bildschirmfoto von 2022-05-12 10-30-52](https://user-images.githubusercontent.com/34514239/168027498-440da686-6d93-4167-9f02-7a10248e0171.png)
Works as expected for me while running (using the latest modlib).

**Comment by appgurueu** [comment]
> Tested with the result:
> simplescreenrecorder-2022-05-12_05.38.42.mp4
> 
> So, looks fine for the static player, but something happens when the player starts to move.

Ah I see now, sorry, forgot to push something. Try https://github.com/appgurueu/modlib/commit/f0d888d44d5154baba032ef57e60d354b38d32fc.

**Comment by sfence** [comment]
Works well now. :)
