### ISSUE TITLE
Add support for 0.4

### ISSUE THREAD

**Issue by IrrlichtMt4** [appgurueu/character_anim#7]
Adding support for 0.4 could be done by using an already existing model from games and then adding the animations to the player model.

**Comment by IrrlichtMt4** [comment]
I'm not that great at code though so I can't show an example for this and I don't know if this is really possible.

**Comment by appgurueu** [comment]
![Bildschirmfoto von 2022-05-14 11-53-55](https://user-images.githubusercontent.com/34514239/168420836-14780edc-c575-45b6-974a-5bbccefa8cc7.png)
![Bildschirmfoto von 2022-05-14 11-53-16](https://user-images.githubusercontent.com/34514239/168420839-766383ac-d5aa-4374-87a0-8b59d34e9938.png)
Added by https://github.com/appgurueu/character_anim/commit/ac23e9f7ddbc9f348e694edea81e1b6ca6e296e7

**Comment by IrrlichtMt4** [comment]
Thanks.

**Comment by appgurueu** [comment]
No problem.
